import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/navigation";
import { ThemeProvider } from "@/providers/theme-provider";
import { CountryProvider } from "@/contexts/CountryContext";

const nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Where in the world?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <CountryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <Navigation />
            <main className="h-full pt-28 md:pt-32 lg:pt-28 px-8 md:px-5 lg:max-w-[1400px] lg:mx-auto">
              {children}
            </main>
          </ThemeProvider>
        </CountryProvider>
      </body>
    </html>
  );
}
